# Generated by Django 5.2.4 on 2025-08-08 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(null=True, upload_to='aboutMe/resume', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), django.core.validators.MaxValueValidator(5242880)]),
        ),
    ]
